Update apache/php install scripts

diff --git a/php/install b/php/install
--- a/php/install
+++ b/php/install
@@ -1,46 +1,30 @@
 #!/usr/bin/env bash
 
-# bash "strict mode"
-set -eu
 
+# vars
 
-# stop install script
-
-	message fail "This PHP install script is deprecated, please attempt a manual install"
-	exit 0
+	HOMEBREW_PATH=$(brew --prefix)
+	apacheconf="$HOMEBREW_PATH/etc/httpd/httpd.conf"
 
 
 # install
-
-	brew install curl --with-openssl 
-	brew install php73 autoconf
-	# brew install mcrypt
-
-	xdebug=$( pecl install xdebug ) || message fail "xdebug" && echo "$xdebug"
-	# apcu=$( pecl install apcu ) || message fail "APCu failed" && echo "$apcu"
-
-	# mcrypyt
-	# brew install mcrypt
-	# sudo pecl install mcrypt-1.0.1
+	# set -eu
+	# brew install curl php autoconf
+	# xdebug=$( pecl install xdebug ) || message fail "xdebug" && echo "$xdebug"
 
 
 # configure
 
-	apacheconf=/usr/local/etc/httpd/httpd.conf
-	phpini=/usr/local/etc/php/7.3/php.ini
+	phpmod="$HOMEBREW_PATH/opt/php/lib/httpd/modules/libphp.so"
 
-	# sudo bash -c "echo extension=/usr/lib/php/20170718/mcrypt.so > /etc/php/7.2/cli/conf.d/mcrypt.ini"
-	# sudo bash -c "echo extension=/usr/lib/php/20170718/mcrypt.so > /etc/php/7.2/apache2/conf.d/mcrypt.ini"
-
-	#apache changes
-	sed -i '' 's|LoadModule php7_module.*|LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so|g' $apacheconf
-
-	if ! grep 'LoadModule php7.*' $apacheconf > /dev/null ; then
-		printf "LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so \n" >> $apacheconf
+	# edit httpd.conf to load php module
+	sed -i '' "s|LoadModule php_module.*|LoadModule php_module $phpmod|g" $apacheconf
+	if ! grep 'LoadModule php_module.*' $apacheconf > /dev/null ; then
+		printf "LoadModule php_module $phpmod \n" >> $apacheconf
 	fi;
 
-	#php directory index
-    sed -i '' 's|DirectoryIndex.*|DirectoryIndex index.php index.html|g' $apacheconf
+	# php directory index
+    sed -i '' 's|DirectoryIndex\(.*\)index.html|DirectoryIndex index.php\1index.html|g' $apacheconf
 
     # add php handler if no matches
     if ! grep 'SetHandler.*application/x-httpd-php' $apacheconf > /dev/null ; then
